# Generated by Django 5.2.17 on 2026-09-13 10:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, unique=True)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('icono', models.CharField(blank=True, help_text='Icono CSS/FontAwesome', max_length=60)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, unique=True)),
                ('contacto', models.CharField(blank=True, max_length=200, verbose_name='Contacto (tel/email/comercial)')),
                ('notas', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ConteoStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(unique=True)),
                ('nota', models.CharField(blank=True, max_length=200)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conteo de stock',
                'verbose_name_plural': 'Conteos de stock',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, unique=True)),
                ('unidad', models.CharField(choices=[('botella', 'Botella'), ('paquete', 'Paquete'), ('caja', 'Caja'), ('lata', 'Lata'), ('botellin', 'Botellín'), ('unidad', 'Unidad'), ('cazoleta', 'Cazoleta')], default='botella', max_length=20)),
                ('stock_minimo', models.PositiveIntegerField(default=0, verbose_name='Stock mínimo deseado')),
                ('stock_actual', models.PositiveIntegerField(default=0, verbose_name='Stock actual')),
                ('precio_medio_copa', models.DecimalField(blank=True, decimal_places=2, help_text='Solo para alcohol: usado en la auditoría de rendimiento.', max_digits=6, null=True, verbose_name='Precio medio por copa (€)')),
                ('copas_por_botella', models.PositiveIntegerField(default=8, verbose_name='Copas por botella')),
                ('es_alcohol', models.BooleanField(default=False, verbose_name='Es alcohol')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='inventario.categoria')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='inventario.proveedor')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['categoria__orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='ConteoStockLinea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_contada', models.PositiveIntegerField(default=0)),
                ('conteo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='inventario.conteostock')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conteos', to='inventario.producto')),
            ],
            options={
                'verbose_name': 'Línea de conteo',
                'verbose_name_plural': 'Líneas de conteo',
                'ordering': ['producto__categoria__orden', 'producto__nombre'],
                'unique_together': {('conteo', 'producto')},
            },
        ),
    ]
