# Generated by Django 5.2.17 on 2026-09-13 10:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('creacion', 'Creación'), ('modificacion', 'Modificación'), ('eliminacion', 'Eliminación'), ('login', 'Login'), ('logout', 'Logout'), ('exportacion', 'Exportación')], db_index=True, max_length=20)),
                ('modelo', models.CharField(max_length=80, verbose_name='Modelo')),
                ('objeto_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('objeto', models.CharField(blank=True, max_length=200, verbose_name='Objeto')),
                ('cambios', models.TextField(blank=True, help_text='Detalle de los campos modificados.')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de auditoría',
                'verbose_name_plural': 'Registro de auditoría',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['modelo', 'objeto_id'], name='core_regist_modelo_a44527_idx')],
            },
        ),
    ]
