# Generated by Django 5.2.17 on 2026-09-13 10:13

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, unique=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='CierreCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha del servicio')),
                ('servicio', models.CharField(choices=[('viernes', 'Viernes'), ('sabado', 'Sábado')], max_length=10, verbose_name='Servicio')),
                ('fondo_caja', models.DecimalField(decimal_places=2, default=Decimal('200.00'), max_digits=10, verbose_name='Fondo de caja inicial (€)')),
                ('efectivo_total_caja', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Efectivo total en caja (€)')),
                ('total_tpv_bizum', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Total TPV / Bizum (€)')),
                ('observaciones', models.TextField(blank=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cierre de caja',
                'verbose_name_plural': 'Cierres de caja',
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PagoPersonal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importe', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Importe pagado (€)')),
                ('cierre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='caja.cierrecaja')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='caja.empleado')),
            ],
            options={
                'verbose_name': 'Pago al personal',
                'verbose_name_plural': 'Pagos al personal',
                'ordering': ['id'],
            },
        ),
    ]
